FROM node:alpine

WORKDIR '/app'

# RUN npm config set proxy http://proxy-web.micron.com:80
# RUN npm config set https-proxy http://proxy-web.micron.com:80
# RUN npm set strict-ssl false

COPY package.json .
RUN npm install

COPY . .
CMD ["npm", "run", "start"]